name: Test

on: [push]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      
      #- run: mkdir -p /home/runner/work

      - name: Request Postment Echo GET
        uses: ./
        with:
          url: 'https://postman-echo.com/get'
          method: 'GET'
      
      - name: Request Postment Echo POST
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          data: '{ "key": "value" }'
      
      - name: RequestEchoBasicAuth
        uses: ./
        with:
          url: 'https://postman-echo.com/basic-auth'
          method: 'GET'
          username: 'postman'
          password: 'password'
          #output: response

      #- run: echo $response > /home/runner/work/somedata.json
      - name: Print the response status
        run: echo ${{ steps.RequestEchoBasicAuth.outputs.status }}
        shell: bash
      - name: Print the response headers
        run: echo ${{ steps.RequestEchoBasicAuth.outputs.headers }}
        shell: bash
      - name: Print_the_response_payload
        run: echo ${{ steps.RequestEchoBasicAuth.outputs.response }}
        shell: bash

      - name: Upload Response
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.RequestEchoBasicAuth.outputs.response }}
          path: /home/runner/work/somedata.json

      #- name: Upload Response
        #uses: actions/upload-artifact@v1
        #with:
        #  name: dist
        #  path: dist

          #FILE=/home/runner/work/historical-weather-data/historical-weather-data`date +"%Y%m%d"`.json

