name: Test

on: [push]

jobs:
  job_1:
    name: Make Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - run: mkdir -p /home/runner/work

      - name: Request Postment Echo GET
        uses: ./
        with:
          url: 'https://postman-echo.com/get'
          method: 'GET'

      - name: Request Postment Echo POST
        uses: ./
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
          data: '{ "key": "value" }'

      - name: Request Postman Echo Basic Auth
        id: basic
        uses: ./
        with:
          url: 'https://postman-echo.com/basic-auth'
          method: 'GET'
          username: 'postman'
          password: 'password'
          #output: response

      - run: echo ${{ steps.basic.outputs.response }}
      - run: echo ${{ steps.basic.outputs.response }} > /home/runner/work/somedata.json

      #- run: echo $response > /home/runner/work/somedata.json
      #- name: Print the response status
      #  run: echo ${{ steps.RequestEchoBasicAuth.outputs.status }}
      #  shell: bash
      #- name: Print the response headers
      #  run: echo ${{ steps.RequestEchoBasicAuth.outputs.headers }}
      #  shell: bash
      #- name: Print the response payload
      #  run: echo ${{ steps.RequestEchoBasicAuth.outputs.response }}
      #  shell: bash

      - name: Upload Response
        uses: actions/upload-artifact@v2
        with:
          name: json_data
          path: /home/runner/work/somedata.json

  job_2:
    name: Upload the output
    runs-on: ubuntu-latest
    needs: [job_1]
    steps:
      - name: Download Response
        uses: actions/upload-artifact@v1
        with:
          name: json_data

          #FILE=/home/runner/work/historical-weather-data/historical-weather-data`date +"%Y%m%d"`.json

